### PR TITLE
99% perfect replication of runescape experience AND FIREMAKING SKILL

### PR DESCRIPTION
**Pull request by Iamgoofball**
exp_formula

### CODE REVIEW

**Comment by Miauw62** [comment]
why does goofball try to insert memescape into everything

**Comment by Iamgoofball** [comment]
@Miauw62 well memed

**Comment by sawu-tg** [comment]
@Miauw62  WATER YOU DOIN' HERE BOYO?

**Comment by sawu-tg** [comment]
@Iamgoofball Test your code, make sure players can still achieve stacks of "Dead" (IE "Dead" in the stat pane), and make sure stuff don't start at 2 or 1 when it should be 0.

**Comment by Xhuis** [comment]
firemaking

**Comment by sawu-tg** [comment]
@Xhuis Thank you for that insightful and useful addition to this already merged PR

**Comment by Xhuis** [comment]
glad to help

**Comment by DaedalusGame** [comment]
:+1:

**Pull request merged**
